//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Evolve.Build
{
    using System;
    using System.Collections.Generic;
    
    public partial class Build
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public string JsonBuild { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string IPTrack { get; set; }
        public string Deleted { get; set; }
    }
}
