//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Evolve.Build
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Role { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public byte[] Image { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string Deleted { get; set; }
    
        public virtual Role Role1 { get; set; }
    }
}
